import useData from "./useData";
import { useRecoilValue } from "recoil";
import { selectedGenres } from "../recoil";

const useGames = () => {
  const selectedGenre = useRecoilValue(selectedGenres); // ✅ now called inside a hook
  return useData("/games", { params: { genres: selectedGenre?.id } }, [
    selectedGenre?.id,
  ]);
};

export default useGames;

// import useData from "./useData";
// import { useRecoilValue } from "recoil";
// import { selectedGenres } from "../recoil";

// const selectedGenre = useRecoilValue(selectedGenres);

// console.log("in use games");
// // const useGames = (selectedGenre) =>
// useData("/games", { prams: { genres: selectedGenre?.id } }, [selectedGenre.id]);
// export default useGames;

// const data = [
//   {
//     id: 12345,
//     slug: "clair-obscur-expedition-33",
//     name: "Clair Obscur: Expedition 33",
//     released: "2025-04-24",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/466/4667f17fdee9ebbcea2049e54f8e2b96.jpg",
//     rating: 4.5,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 8000, percent: 80 },
//       { id: 4, title: "recommended", count: 1500, percent: 15 },
//       { id: 3, title: "meh", count: 400, percent: 4 },
//       { id: 1, title: "skip", count: 100, percent: 1 },
//     ],
//     ratings_count: 10000,
//     reviews_text_count: "200",
//     added: 5000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 90,
//     playtime: 40,
//     suggestions_count: 100,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 2, name: "Mature", slug: "mature" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//       {
//         platform: {
//           id: 186,
//           name: "Xbox",
//           slug: "xbox",
//         },
//       },
//     ],
//   },
//   {
//     id: 67890,
//     slug: "assassins-creed-shadows",
//     name: "Assassin's Creed Shadows",
//     released: "2025-03-20",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/526/526881e0f5f8c1550e51df3801f96ea3.jpg",
//     rating: 4.7,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 12750, percent: 85 },
//       { id: 4, title: "recommended", count: 1500, percent: 10 },
//       { id: 3, title: "meh", count: 450, percent: 3 },
//       { id: 1, title: "skip", count: 300, percent: 2 },
//     ],
//     ratings_count: 15000,
//     reviews_text_count: "300",
//     added: 8000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 92,
//     playtime: 50,
//     suggestions_count: 200,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 2, name: "Mature", slug: "mature" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//       {
//         platform: {
//           id: 186,
//           name: "Xbox",
//           slug: "xbox",
//         },
//       },
//       { platform: { id: 166, name: "mac", slug: "mac" } },
//       { platform: { id: 193, name: "iPad", slug: "ipad" } },
//     ],
//   },
//   {
//     id: 11223,
//     slug: "doom-the-dark-ages",
//     name: "Doom: The Dark Ages",
//     released: "2025-05-15",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/018/01897340a06b9ed8e92ed1cc1b1eecb9.jpg",
//     rating: 4.6,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 18000, percent: 90 },
//       { id: 4, title: "recommended", count: 1400, percent: 7 },
//       { id: 3, title: "meh", count: 400, percent: 2 },
//       { id: 1, title: "skip", count: 200, percent: 1 },
//     ],
//     ratings_count: 20000,
//     reviews_text_count: "400",
//     added: 10000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 93,
//     playtime: 60,
//     suggestions_count: 300,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 2, name: "Mature", slug: "mature" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//       {
//         platform: {
//           id: 186,
//           name: "Xbox",
//           slug: "xbox",
//         },
//       },
//     ],
//   },
//   {
//     id: 33445,
//     slug: "replaced",
//     name: "Replaced",
//     released: "2025-06-01",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/041/041e04184322bc859d617b790d8bfab9.jpg",
//     rating: 4.3,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 9000, percent: 75 },
//       { id: 4, title: "recommended", count: 2400, percent: 20 },
//       { id: 3, title: "meh", count: 360, percent: 3 },
//       { id: 1, title: "skip", count: 240, percent: 2 },
//     ],
//     ratings_count: 12000,
//     reviews_text_count: "250",
//     added: 6000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 88,
//     playtime: 45,
//     suggestions_count: 150,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//       {
//         platform: {
//           id: 186,
//           name: "Xbox",
//           slug: "xbox",
//         },
//       },
//     ],
//   },
//   {
//     id: 55667,
//     slug: "south-of-midnight",
//     name: "South of Midnight",
//     released: "2025-06-05",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/734/73451dc0abd013bee5b7d88faaacec11.jpg",
//     rating: 4.4,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 8800, percent: 80 },
//       { id: 4, title: "recommended", count: 1650, percent: 15 },
//       { id: 3, title: "meh", count: 330, percent: 3 },
//       { id: 1, title: "skip", count: 220, percent: 2 },
//     ],
//     ratings_count: 11000,
//     reviews_text_count: "220",
//     added: 5500,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 89,
//     playtime: 35,
//     suggestions_count: 120,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 1, name: "Everyone 10+", slug: "everyone10" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: {
//           id: 186,
//           name: "Xbox",
//           slug: "xbox",
//         },
//       },
//     ],
//   },
//   {
//     id: 77889,
//     slug: "the-wolf-among-us-2",
//     name: "The Wolf Among Us 2",
//     released: "2025-06-10",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/845/84539f8f33fea2c753cca0ce3a6d168f.jpg",
//     rating: 4.8,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 14250, percent: 95 },
//       { id: 4, title: "recommended", count: 450, percent: 3 },
//       { id: 3, title: "meh", count: 150, percent: 1 },
//       { id: 1, title: "skip", count: 150, percent: 1 },
//     ],
//     ratings_count: 15000,
//     reviews_text_count: "300",
//     added: 7000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 94,
//     playtime: 25,
//     suggestions_count: 180,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 2, name: "Mature", slug: "mature" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//       {
//         platform: {
//           id: 186,
//           name: "Xbox",
//           slug: "xbox",
//         },
//       },
//     ],
//   },
//   {
//     id: 10101,
//     slug: "the-elder-scrolls-iv-oblivion-remastered",
//     name: "The Elder Scrolls IV: Oblivion Remastered",
//     released: "2025-11-15",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/e56/e56b78444369c6b3ae92ae7f669bf8cd.jpg",
//     rating: 4.8,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 12000, percent: 80 },
//       { id: 4, title: "recommended", count: 2000, percent: 13 },
//       { id: 3, title: "meh", count: 600, percent: 4 },
//       { id: 1, title: "skip", count: 300, percent: 3 },
//     ],
//     ratings_count: 14900,
//     reviews_text_count: "400",
//     added: 9500,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 91,
//     playtime: 60,
//     suggestions_count: 220,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 2, name: "Mature", slug: "mature" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//     ],
//   },
//   {
//     id: 10102,
//     slug: "death-stranding-2-on-the-beach",
//     name: "Death Stranding 2: On The Beach",
//     released: "2025-12-01",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/b85/b85bc300d42588af66fb516b7563f74f.jpg",
//     rating: 4.6,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 11000, percent: 75 },
//       { id: 4, title: "recommended", count: 2500, percent: 17 },
//       { id: 3, title: "meh", count: 700, percent: 5 },
//       { id: 1, title: "skip", count: 200, percent: 3 },
//     ],
//     ratings_count: 14600,
//     reviews_text_count: "350",
//     added: 10000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 88,
//     playtime: 55,
//     suggestions_count: 180,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 3, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: { id: 187, name: "PlayStation", slug: "playstation" },
//       },
//     ],
//   },
//   {
//     id: 10103,
//     slug: "the-first-berserker-khazan",
//     name: "The First Berserker: Khazan",
//     released: "2025-10-10",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/ace/ace798425ecf3a1881309cf12f059aa0.jpg",
//     rating: 4.2,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 8500, percent: 70 },
//       { id: 4, title: "recommended", count: 2500, percent: 20 },
//       { id: 3, title: "meh", count: 700, percent: 6 },
//       { id: 1, title: "skip", count: 300, percent: 4 },
//     ],
//     ratings_count: 12000,
//     reviews_text_count: "220",
//     added: 6000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 85,
//     playtime: 50,
//     suggestions_count: 90,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       { platform: { id: 18, name: "PlayStation", slug: "playstation" } },
//     ],
//   },
//   {
//     id: 10104,
//     slug: "grand-theft-auto-vi",
//     name: "Grand Theft Auto VI",
//     released: "2026-03-20",
//     tba: true,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/734/7342a1cd82c8997ec620084ae4c2e7e4.jpg",
//     rating: 0,
//     rating_top: 5,
//     ratings: [],
//     ratings_count: 0,
//     reviews_text_count: "0",
//     added: 0,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: null,
//     playtime: 0,
//     suggestions_count: 0,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: null,
//     parent_platforms: [
//       { platform: { id: 18, name: "PlayStation", slug: "playstation" } },
//     ],
//   },
//   {
//     id: 10105,
//     slug: "tainted-grail-the-fall-of-avalon",
//     name: "Tainted Grail: The Fall of Avalon",
//     released: "2025-08-15",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/c73/c73cd3a8bc46ccd7d62621bc19766f01.jpg",
//     rating: 4.0,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 7200, percent: 65 },
//       { id: 4, title: "recommended", count: 2500, percent: 22 },
//       { id: 3, title: "meh", count: 900, percent: 8 },
//       { id: 1, title: "skip", count: 300, percent: 5 },
//     ],
//     ratings_count: 11000,
//     reviews_text_count: "180",
//     added: 4500,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 83,
//     playtime: 45,
//     suggestions_count: 100,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 41, name: "Ios", slug: "ios" } },
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       { platform: { id: 18, name: "PlayStation", slug: "playstation" } },
//     ],
//   },
//   {
//     id: 10106,
//     slug: "the-outer-worlds-2",
//     name: "The Outer Worlds 2",
//     released: "2026-02-22",
//     tba: true,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/67d/67de45e83579bd921dffbaf3b4700c9d.jpg",
//     rating: 0,
//     rating_top: 5,
//     ratings: [],
//     ratings_count: 0,
//     reviews_text_count: "0",
//     added: 0,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: null,
//     playtime: 0,
//     suggestions_count: 0,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: null,
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       { platform: { id: 18, name: "PlayStation", slug: "playstation" } },
//     ],
//   },
//   {
//     id: 10107,
//     slug: "atomfall",
//     name: "Atomfall",
//     released: "2025-09-30",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/5b0/5b044517a778ed67435bd71efc98395d.jpg",
//     rating: 4.3,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 6000, percent: 65 },
//       { id: 4, title: "recommended", count: 2400, percent: 26 },
//       { id: 3, title: "meh", count: 700, percent: 7 },
//       { id: 1, title: "skip", count: 300, percent: 2 },
//     ],
//     ratings_count: 9200,
//     reviews_text_count: "150",
//     added: 4300,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 86,
//     playtime: 38,
//     suggestions_count: 80,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [{ platform: { id: 4, name: "PC", slug: "pc" } }],
//   },
//   {
//     id: 10108,
//     slug: "mafia-the-old-country",
//     name: "Mafia: The Old Country",
//     released: "2025-07-20",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/screenshots/6d4/6d4df2db0867a330630db150095f2064.jpg",
//     rating: 4.5,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 8000, percent: 70 },
//       { id: 4, title: "recommended", count: 2800, percent: 24 },
//       { id: 3, title: "meh", count: 700, percent: 5 },
//       { id: 1, title: "skip", count: 200, percent: 1 },
//     ],
//     ratings_count: 11700,
//     reviews_text_count: "210",
//     added: 7000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 87,
//     playtime: 48,
//     suggestions_count: 110,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 2, name: "Mature", slug: "mature" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       { platform: { id: 18, name: "PlayStation", slug: "playstation" } },
//     ],
//   },
//   {
//     id: 10109,
//     slug: "blue-prince",
//     name: "Blue Prince",
//     released: "2025-10-05",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/258/258f88a911a4233d4f21c2f91dceb892.jpg",
//     rating: 4.1,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 5300, percent: 60 },
//       { id: 4, title: "recommended", count: 2700, percent: 30 },
//       { id: 3, title: "meh", count: 800, percent: 7 },
//       { id: 1, title: "skip", count: 200, percent: 3 },
//     ],
//     ratings_count: 9000,
//     reviews_text_count: "140",
//     added: 4000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 82,
//     playtime: 40,
//     suggestions_count: 70,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: {
//           id: 7,
//           name: "Nintendo",
//           slug: "nintendo",
//         },
//       },
//     ],
//   },
//   {
//     id: 10110,
//     slug: "star-citizen",
//     name: "Star Citizen",
//     released: "2025-11-20",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/crop/600/400/games/926/9268bcfde5bea6f457a6833a55b653e9.jpg",
//     rating: 4.4,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 9000, percent: 72 },
//       { id: 4, title: "recommended", count: 2700, percent: 22 },
//       { id: 3, title: "meh", count: 700, percent: 5 },
//       { id: 1, title: "skip", count: 400, percent: 1 },
//     ],
//     ratings_count: 12800,
//     reviews_text_count: "230",
//     added: 8000,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 89,
//     playtime: 55,
//     suggestions_count: 140,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 3, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       { platform: { id: 1, name: "Xbox One", slug: "xbox-one" } },
//     ],
//   },
//   {
//     id: 10111,
//     slug: "mandragora-whispers-of-the-witch-tree",
//     name: "Mandragora: Whispers of the Witch Tree",
//     released: "2025-12-10",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/d0a/d0a69e26b006172a7ecbce4a3a8f33bd.jpg",
//     rating: 4.0,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 6800, percent: 65 },
//       { id: 4, title: "recommended", count: 2200, percent: 21 },
//       { id: 3, title: "meh", count: 900, percent: 9 },
//       { id: 1, title: "skip", count: 300, percent: 5 },
//     ],
//     ratings_count: 10200,
//     reviews_text_count: "170",
//     added: 4900,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 83,
//     playtime: 42,
//     suggestions_count: 85,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [{ platform: { id: 4, name: "PC", slug: "pc" } }],
//   },
//   {
//     id: 10112,
//     slug: "the-alters",
//     name: "The Alters",
//     released: "2025-09-15",
//     tba: false,
//     background_image:
//       "https://media.rawg.io/media/resize/640/-/games/457/457f5a7f204b1bb3dead55aed1b2738f.jpg",
//     rating: 4.1,
//     rating_top: 5,
//     ratings: [
//       { id: 5, title: "exceptional", count: 5500, percent: 62 },
//       { id: 4, title: "recommended", count: 2500, percent: 28 },
//       { id: 3, title: "meh", count: 600, percent: 7 },
//       { id: 1, title: "skip", count: 200, percent: 3 },
//     ],
//     ratings_count: 8800,
//     reviews_text_count: "130",
//     added: 4600,
//     added_by_status: {
//       yet: 0,
//       owned: 0,
//       beaten: 0,
//       dropped: 0,
//       playing: 0,
//       toplay: 0,
//     },
//     metacritic: 84,
//     playtime: 40,
//     suggestions_count: 70,
//     updated: "2025-06-09T09:26:09Z",
//     esrb_rating: { id: 4, name: "Teen", slug: "teen" },
//     parent_platforms: [
//       { platform: { id: 4, name: "PC", slug: "pc" } },
//       {
//         platform: {
//           id: 7,
//           name: "Nintendo",
//           slug: "nintendo",
//         },
//       },
//     ],
//   },
// ];
// const useGames = () => {
//   return { data, isLoading: false, error: "" };
// };
